package graph

// Code generated by github.com/99designs/gqlgen version v0.17.75

import (
	"context"

	"github.com/One-Frequency/MusicRAG/backend/graph/generated"
)

// queryResolver binds our query implementations.
type queryResolver struct{ *Resolver }

// Hello is the resolver for the hello field in your GraphQL schema.
func (r *queryResolver) Hello(ctx context.Context, name string) (string, error) {
    return "Hello, " + name + "!", nil
}

// Query returns the implementation for the root Query type.
func (r *Resolver) Query() generated.QueryResolver {
    return &queryResolver{r}
}